"""
comment_formatter.py - Formats DNS review results into a GitHub PR comment.
"""

from typing import Any, Mapping

def format_pr_comment(filename: str, validator_result: Mapping[str, Any], llm_result: Mapping[str, Any]) -> str:
    """
    Format the review results into a GitHub markdown PR comment.
    
    Args:
        filename (str): The name of the zone file reviewed.
        validator_result (dict): The result dictionary from the validator.
        llm_result (dict): The result dictionary from the LLM reviewer.
        
    Returns:
        str: A formatted markdown string conforming to the exact PR comment specifications.
    """
    risk_circles = {
        "CRITICAL": "🔴",
        "HIGH": "🔴",
        "MEDIUM": "🟠",
        "LOW": "🟢",
        "CLEAN": "🟢"
    }
    
    severity_emojis = {
        "CRITICAL": "❌",
        "WARNING": "⚠️",
        "INFO": "ℹ️"
    }
    
    risk_level = llm_result.get("risk_level", "CLEAN").upper()
    risk_circle = risk_circles.get(risk_level, "🟢")
    
    safe_to_merge = llm_result.get("safe_to_merge", True)
    safe_text = "✅ Yes" if safe_to_merge else "❌ No"
    
    model_used = llm_result.get("model_used", "none")
    llm_available = llm_result.get("llm_available", False)
    
    summary = llm_result.get("summary", "No summary provided.")
    reviewer_note = llm_result.get("reviewer_note", "")
    
    findings_md = ""
    llm_findings = llm_result.get("llm_findings", [])
    
    if not llm_findings:
        findings_md = "No issues found.\n\n"
    else:
        for finding in llm_findings:
            sev = finding.get("severity", "INFO").upper()
            sev_emoji = severity_emojis.get(sev, "ℹ️")
            title = finding.get("title", "Finding")
            desc = finding.get("description", "No description")
            rec = finding.get("recommendation", "No recommendation")
            
            findings_md += f"#### {sev_emoji} {sev} — {title}\n"
            findings_md += f"**Why it's risky:** {desc}\n"
            findings_md += f"**Recommendation:** {rec}\n\n---\n\n"
            
    v_valid = validator_result.get("valid", False)
    v_valid_text = "✅ Yes" if v_valid else "❌ No"
    v_errors = validator_result.get("errors", [])
    v_errors_text = ", ".join(v_errors) if v_errors else "None"
    
    comment = f"""## 🔍 DNS Zone Review Bot — `{filename}`

### 📊 Risk Assessment
| Field | Value |
|-------|-------|
| **Risk Level** | {risk_circle} {risk_level} |
| **Safe to Merge** | {safe_text} |
| **LLM Model** | {model_used} |

### 📝 Summary
{summary}

### 🚨 Findings

{findings_md.strip()}

### ✅ Validator Results
- Syntax valid: {v_valid_text}
- Records checked: N/A
- Errors: {v_errors_text}

### 💬 Reviewer Note
{reviewer_note}

---
<sub>🤖 Generated by DNS Zone Reviewer Bot</sub>"""

    if not llm_available and "LLM review skipped" not in reviewer_note:
        comment += "\n\n⚠️ LLM review skipped - running validator results only"
        
    return comment
