import pytest
from unittest.mock import patch, MagicMock
from pathlib import Path
import requests

from validator import validate_zone
from llm_reviewer import analyze_with_llm
from comment_formatter import format_pr_comment
from main import main

@patch("llm_reviewer.requests.post")
def test_full_pipeline_clean_zone(mock_post):
    mock_post.side_effect = requests.exceptions.ConnectionError("Connection refused")
    
    zone_content = Path("sample_data/clean_zone.txt").read_text(encoding="utf-8")
    val_result = validate_zone(zone_content, "zones/clean.example.com.txt")
    llm_result = analyze_with_llm("", val_result["findings"], "zones/clean.example.com.txt")
    
    assert llm_result["risk_level"] in ("LOW", "CLEAN")
    assert llm_result["safe_to_merge"] is True

@patch("llm_reviewer.requests.post")
def test_full_pipeline_risky_zone(mock_post):
    mock_post.side_effect = requests.exceptions.ConnectionError("Connection refused")
    
    zone_content = Path("sample_data/risky_zone.txt").read_text(encoding="utf-8")
    val_result = validate_zone(zone_content, "zones/risky.example.com.txt")
    llm_result = analyze_with_llm("", val_result["findings"], "zones/risky.example.com.txt")
    
    assert any(f["severity"] == "CRITICAL" for f in val_result["findings"])
    assert llm_result["safe_to_merge"] is False

@patch("llm_reviewer.requests.post")
def test_full_pipeline_critical_zone(mock_post):
    mock_post.side_effect = requests.exceptions.ConnectionError("Connection refused")
    
    zone_content = Path("sample_data/critical_zone.txt").read_text(encoding="utf-8")
    val_result = validate_zone(zone_content, "zones/critical.example.com.txt")
    llm_result = analyze_with_llm("", val_result["findings"], "zones/critical.example.com.txt")
    
    has_critical = any(f["severity"] == "CRITICAL" for f in val_result["findings"])
    assert not val_result["valid"] or has_critical

def test_comment_formatter_clean_output():
    val_result = {"valid": True, "errors": [], "findings": []}
    llm_result = {
        "risk_level": "CLEAN", 
        "safe_to_merge": True, 
        "model_used": "llama3.2", 
        "llm_available": True, 
        "summary": "Looks good", 
        "llm_findings": [], 
        "reviewer_note": ""
    }
    
    comment = format_pr_comment("clean_zone.txt", val_result, llm_result)
    
    assert "CLEAN" in comment or "LOW" in comment
    assert "Safe to Merge" in comment
    assert "DNS Zone Review Bot" in comment or "Generated by DNS Zone Reviewer Bot" in comment

def test_comment_formatter_critical_output():
    val_result = {"valid": False, "errors": ["Parse error"], "findings": []}
    llm_result = {
        "risk_level": "CRITICAL", 
        "safe_to_merge": False, 
        "model_used": "llama3.2", 
        "llm_available": True, 
        "summary": "Bad zone", 
        "llm_findings": [], 
        "reviewer_note": ""
    }
    
    comment = format_pr_comment("critical_zone.txt", val_result, llm_result)
    
    assert "CRITICAL" in comment
    assert "❌" in comment

@patch("main.get_changed_zones")
@patch("main.analyze_with_llm")
def test_main_exits_with_code_1_on_critical(mock_llm, mock_differ):
    mock_differ.return_value = [
        {"filename": "zones/risky_zone.txt", "before": "", "after": "content", "diff": ""}
    ]
    mock_llm.return_value = {
        "risk_level": "CRITICAL",
        "safe_to_merge": False,
        "llm_findings": [],
        "model_used": "mock",
        "llm_available": True
    }
    
    with pytest.raises(SystemExit) as excinfo:
        main()
    
    assert excinfo.value.code == 1
